server:
  port: 18080

spring:
  application:
    name: spring-ai-alibaba-helloworld
  config:
    import: optional:classpath:apiKey.yml # 使用optional防止文件不存在时报错
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_memory?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  ai:
    dashscope:
      api-key: ${ali.api-key}
      embedding:
        options:
          model: text-embedding-v4     # 指定百炼的向量化模型
          dimensions: 1024              # 🚨 核心避坑：明确指定输出维度为 768
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always  # 启动时自动创建表
    alibaba:
      playground:
        bailian:
          enable: true
          index-name: "drafire-test" # 例如: saa-playground-2

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG