server:
  port: 18080

spring:
  application:
    name: spring-ai-alibaba-helloworld
  config:
    import: optional:classpath:apiKey.yml # 使用optional防止文件不存在时报错
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_memory?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456

  ai:
    dashscope:
      api-key: ${ali.api-key}
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always  # 启动时自动创建表

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG